services:
  anonycow-server:
    build: .
    image: "memm9999/anonycow-server"
    command:
      - /bin/sh
      - -c
      - |
        npx prisma db push
        create-admin --username=mohammed --password=123456789
        nohup ./runPrismaStudio.sh &
        node index.js
    ports:
      - "80:80"
    depends_on:
      - redis-stack-server
    networks:
      - anonycow-network

  redis-stack-server:
    image: "redis/redis-stack-server:latest"
    networks:
      - anonycow-network

networks:
  anonycow-network: {}
